/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "recttoclient.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragfact.c"
#include "fakefullscreenclient.c"
#include "focusadjacenttag.c"
#include "focusdir.c"
#include "focusmaster.c"
#include "fullscreen.c"
#include "pertag.c"
#include "placedir.c"
#include "placemouse.c"
#include "roundedcorners.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "unfloatvisible.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_deck.c"
#include "layout_monocle.c"
#include "layout_tile.c"

