/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_status.h"
#include "bar_powerline_tags.h"
#include "bar_status.h"
#include "bar_statuscmd.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "recttoclient.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragfact.h"
#include "exresize.h"
#include "fakefullscreenclient.h"
#include "floatpos.h"
#include "focusdir.h"
#include "focusmaster.h"
#include "fullscreen.h"
#include "movestack.h"
#include "nomodbuttons.h"
#include "placedir.h"
#include "placemouse.h"
#include "rotatestack.h"
#include "roundedcorners.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_deck.h"
#include "layout_flextile-deluxe.h"
#include "layout_monocle.h"
#include "layout_tile.h"

