/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_ltsymbol.c"
#include "bar_powerline_status.c"
#include "bar_powerline_tags.c"
#include "bar_status.c"
#include "bar_statuscmd.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "recttoclient.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragfact.c"
#include "exresize.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "focusdir.c"
#include "focusmaster.c"
#include "fullscreen.c"
#include "movestack.c"
#include "placedir.c"
#include "placemouse.c"
#include "rotatestack.c"
#include "roundedcorners.c"
#include "swallow.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_flextile-deluxe.c"

